### ISSUE TITLE
Introduce Gatsby Image Plugin

### ISSUE THREAD

**Issue by ohrie** [FixMyBerlin/fixmy.rsv#13]
For better image handling we could introduce the `gatsby-plugin-image`. It automatically creates srcsets and providing different sizes for responsive pages in different formats. It also handles placeholder images, when internet connection is bad.

It provides the `<StaticImage />` component.

See also https://www.gatsbyjs.com/plugins/gatsby-plugin-image/ and docs: https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-plugin-image/

- [ ] Add dependency
- [ ] Replace all appropriate images with new Component

**Comment by tordans** [comment]
I thought this is already part of the setup. But if not, we should add it. We have it running in https://github.com/FixMyBerlin/fixmy.fahrradparken/blob/develop/package.json#L45, eg on https://radparken.info/fachinformationen/leitfaeden-studien/ and https://radparken.info/fachinformationen/best-practice/.

**Comment by ohrie** [comment]
@rush42 May you could try to integrate the plugin and replace all images which are not part of the design? That would be awesome!
