### ISSUE TITLE
Develop an automated process to simplify GeoJSON geometry for usage in static images and delivering files

### ISSUE THREAD

**Issue by ohrie** [FixMyBerlin/fixmy.rsv#61]
## The Problem
URLs for retrieving static images are too long, therefore the GeoJSON needs to be reduced in its geometry level of detail.

## Tasks
- [ ]
- [ ]
- [ ]

FIY @rush42

**Comment by rush42** [comment]
maybe [@turf/simplify](https://www.npmjs.com/package/@turf/simplify) is useful for this
