### ISSUE TITLE
Resolve static image unavailable background tiles 

### ISSUE THREAD

**Issue by ohrie** [FixMyBerlin/fixmy.rsv#63]
## What are the steps to reproduce this issue?

1. Go to https://radschnellverbindungen.info/steckbriefe/

## What happens?
Some cards don't have an image, but it only shows the geometry of the RSV , not the map background tiles

## What were you expecting to happen?
Every map should have background tiles

## Any logs, error output, etc?
no seen.

## Which version/branch do you run?
develop

**Comment by rush42** [comment]
Update: We're in contact with the MapTiler support for fixing this

**Comment by rush42** [comment]
Apparently they have fixed the bug after our feedbag.
