### ISSUE TITLE
Suggested changes to MetaJSON

### ISSUE THREAD

**Issue by rush42** [FixMyBerlin/fixmy.rsv#65]
For the planned features of [radschnellverbindungen.info](https://radschnellverbindungen.info/) we need the following adaptations in the MetaJSON schema:
(descending order of priority)

- [x] include the total length of every RSV
- [x] split `from` and `to` attributes, e.g.: `from: string` -> `from: {city: string, state: string}` 
- [ ] name `id` attribute consistent with the geoJSON files: currently the corresponding geoJSON attribute is `name` (which is also a foreign key in the geoJSON specification... thus changing `name` -> `id`  might be better)

**Comment by ohrie** [comment]
This is on hold.
